#include "http.h"
#include "index.h"
#include <esp_err.h>
#include <esp_http_server.h>

esp_err_t index_handler(httpd_req_t *req)
{
    const char *html_text = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>CW Sender</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            margin: 20px;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            position: relative;\n"
"        }\n"
"        header {\n"
"            display: flex;\n"
"            justify-content: space-between;\n"
"            align-items: center;\n"
"            width: 100%;\n"
"            max-width: 400px;\n"
"            margin-bottom: 20px;\n"
"        }\n"
"        header h1 {\n"
"            margin: 0;\n"
"            text-align: center;\n"
"            flex-grow: 1;\n"
"        }\n"
"        #settingsButton {\n"
"            background-color: #007BFF;\n"
"            color: white;\n"
"            border: none;\n"
"            border-radius: 5px;\n"
"            cursor: pointer;\n"
"            padding: 10px 15px;\n"
"        }\n"
"        #settingsButton:hover {\n"
"            background-color: #0056b3;\n"
"        }\n"
"        form {\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: flex-start;\n"
"            width: 100%;\n"
"            max-width: 400px;\n"
"        }\n"
"        label {\n"
"            margin-top: 10px;\n"
"        }\n"
"        input {\n"
"            margin-bottom: 10px;\n"
"            padding: 5px;\n"
"            width: 100%;\n"
"            box-sizing: border-box;\n"
"        }\n"
"        button {\n"
"            padding: 10px 15px;\n"
"            margin-top: 10px;\n"
"            align-self: flex-start;\n"
"        }\n"
"        #status {\n"
"            margin-top: 20px;\n"
"            padding: 10px;\n"
"            border: 1px solid #ccc;\n"
"            background-color: #f9f9f9;\n"
"            width: 100%;\n"
"            max-width: 400px;\n"
"            box-sizing: border-box;\n"
"        }\n"
"        #status h3 {\n"
"            margin: 0 0 10px 0;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <header>\n"
"        <h1>CW Sender</h1>\n"
"        <button id=\"settingsButton\" onclick=\"navigateToSettings()\">Settings</button>\n"
"    </header>\n"
"    <form>\n"
"        <label for=\"message\">Message:</label>\n"
"        <input type=\"text\" id=\"message\" placeholder=\"Enter your message\">\n"
"\n"
"        <button type=\"button\" onclick=\"sendMorse()\">Send Morse Code</button>\n"
"    </form>\n"
"\n"
"    <div id=\"status\">\n"
"        <h3>Status</h3>\n"
"        <p id=\"statusText\">Loading...</p>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        // Automatically convert message input to uppercase\n"
"        document.getElementById('message').addEventListener('input', function (event) {\n"
"            event.target.value = event.target.value.toUpperCase();\n"
"        });\n"
"\n"
"        // Function to fetch and display the current status\n"
"        async function getStatus() {\n"
"            try {\n"
"                const response = await fetch('/api/status');\n"
"                if (!response.ok) {\n"
"                    throw new Error('Failed to fetch status');\n"
"                }\n"
"\n"
"                const data = await response.json();\n"
"                document.getElementById('statusText').innerText = `Status: ${data.status} Busy: ${data.busy ? 'Yes' : 'No'}`;\n"
"            } catch (error) {\n"
"                console.error('Error fetching status:', error);\n"
"                document.getElementById('statusText').innerText = 'Error fetching status';\n"
"            }\n"
"        }\n"
"\n"
"        // Function to fetch the current message and set it in the input field\n"
"        async function loadCurrentMessage() {\n"
"            try {\n"
"                const response = await fetch('/api/message');\n"
"                if (!response.ok) {\n"
"                    throw new Error('Failed to fetch current message');\n"
"                }\n"
"                const data = await response.json();\n"
"                document.getElementById('message').value = data.message ? decodeURIComponent(data.message) : '';\n"
"            } catch (error) {\n"
"                console.error('Error fetching current message:', error);\n"
"                document.getElementById('statusText').innerText = 'Error fetching current message';\n"
"            }\n"
"        }\n"
"\n"
"        // Function to send a message using the Morse API\n"
"        async function sendMorse() {\n"
"            const message = document.getElementById('message').value;\n"
"\n"
"            if (!message) {\n"
"                document.getElementById('statusText').innerText = 'Please enter a message';\n"
"                return;\n"
"            }\n"
"\n"
"            try {\n"
"                const response = await fetch('/api/morse', {\n"
"                    method: 'POST',\n"
"                    headers: { 'Content-Type': 'application/json' },\n"
"                    body: JSON.stringify({ message }) // Send the message as JSON\n"
"                });\n"
"                if (!response.ok) {\n"
"                    throw new Error('Failed to send Morse code');\n"
"                }\n"
"                const data = await response.json();\n"
"                document.getElementById('statusText').innerText = data.result || 'Morse code sent successfully';\n"
"            } catch (error) {\n"
"                console.error('Error sending Morse code:', error);\n"
"                document.getElementById('statusText').innerText = 'Error sending Morse code';\n"
"            }\n"
"        }\n"
"\n"
"        // Function to navigate to the settings page\n"
"        function navigateToSettings() {\n"
"            window.location.href = '/settings';\n"
"        }\n"
"\n"
"        // Fetch the status every second\n"
"        setInterval(getStatus, 1000);\n"
"\n"
"        // Fetch the current message and status when the page loads\n"
"        window.onload = function () {\n"
"            loadCurrentMessage();\n"
"            getStatus();\n"
"        };\n"
"    </script>\n"
"</body>\n"
"</html>\n";

    httpd_resp_set_type(req, "text/html");         // Set response type to HTML
    httpd_resp_send(req, html_text, strlen(html_text));      // Send the HTML content
    return ESP_OK;
}

void register_index_page(void)
{
    register_html_page("/", HTTP_GET, index_handler);
}
